"""add is_deleted to applications

Revision ID: 6a7ada852268
Revises: f2cabdfae328
Create Date: 2026-08-06 19:01:29.455017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7ada852268'
down_revision: Union[str, None] = 'f2cabdfae328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_deleted')
    # ### end Alembic commands ###
